#!/bin/sh
#
# @name LS2N Hexarotor
#
# @type Hexa +
#
# @maintainer Julian Erskine <julian.erskine@ls2n.fr>
#

. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCH_P 6.0
	param set MC_ROLLRATE_P 0.15
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLL_P 6.0
	param set MPC_XY_VEL_I_ACC 4
	param set MPC_XY_VEL_P_ACC 3
fi

set MAV_TYPE 13

set MIXER hexa_+
